<?php
session_start();require __DIR__.'/../config/database.php';require __DIR__.'/../includes/helpers.php';require_admin();
if($_SERVER['REQUEST_METHOD']==='POST'){
  verify_csrf(); $action=$_POST['action']??'';
  if($action==='save'){
    $id=(int)($_POST['id']??0); $data=[(int)$_POST['category_id'],trim($_POST['name']),trim($_POST['address']),trim($_POST['description']),max(0,(float)$_POST['average_cost']),max(0,min(5,(float)$_POST['rating'])),trim($_POST['image_url'])];
    if($id){$pdo->prepare('UPDATE locations SET category_id=?,name=?,address=?,description=?,average_cost=?,rating=?,image_url=? WHERE id=?')->execute([...$data,$id]);flash('success','Đã cập nhật địa điểm.');}
    else{$pdo->prepare('INSERT INTO locations(category_id,name,address,description,average_cost,rating,image_url) VALUES(?,?,?,?,?,?,?)')->execute($data);flash('success','Đã thêm địa điểm.');}
  } elseif($action==='delete') {$pdo->prepare('DELETE FROM locations WHERE id=?')->execute([(int)$_POST['id']]);flash('info','Đã xóa địa điểm.');}
  redirect('admin/locations.php');
}
$cats=$pdo->query('SELECT * FROM categories ORDER BY name')->fetchAll();
$rows=$pdo->query('SELECT l.*,c.name category_name FROM locations l JOIN categories c ON c.id=l.category_id ORDER BY l.id DESC')->fetchAll();
$pageTitle='Admin · Locations';include __DIR__.'/../includes/header.php';show_flash();
?><div class="page-shell"><div class="d-flex justify-content-between align-items-center"><div><div class="eyebrow">ADMIN</div><h1 class="fw-800 mb-0">Locations</h1></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#locModal" onclick="resetLocationForm()">+ Thêm</button></div><div class="table-responsive mt-4"><table class="table align-middle"><thead><tr><th>Tên</th><th>Danh mục</th><th>Rating</th><th>Cost</th><th></th></tr></thead><tbody>
<?php foreach($rows as $r): ?><tr><td><strong><?= e($r['name']) ?></strong><div class="small text-secondary"><?= e($r['address']) ?></div></td><td><?= e($r['category_name']) ?></td><td>⭐ <?= e($r['rating']) ?></td><td><?= number_format($r['average_cost'],0,',','.') ?>đ</td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#locModal" onclick='editLocation(<?= json_encode($r,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?>)'>Sửa</button><form method="post" class="d-inline" onsubmit="return confirm('Xóa địa điểm này?')"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= $r['id'] ?>"><button class="btn btn-sm btn-link text-danger">Xóa</button></form></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="modal fade" id="locModal"><div class="modal-dialog modal-lg"><div class="modal-content"><form method="post"><div class="modal-header"><h5 class="modal-title fw-800" id="locTitle">Thêm địa điểm</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" id="locId"><div class="row g-3"><div class="col-md-8"><label class="form-label">Tên</label><input class="form-control" name="name" id="locName" required></div><div class="col-md-4"><label class="form-label">Danh mục</label><select class="form-select" name="category_id" id="locCategory"><?php foreach($cats as $c): ?><option value="<?= $c['id'] ?>"><?= e($c['name']) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">Địa chỉ</label><input class="form-control" name="address" id="locAddress" required></div><div class="col-12"><label class="form-label">Mô tả</label><textarea class="form-control" name="description" id="locDescription"></textarea></div><div class="col-md-4"><label class="form-label">Chi phí</label><input class="form-control" type="number" min="0" name="average_cost" id="locCost"></div><div class="col-md-4"><label class="form-label">Rating</label><input class="form-control" type="number" step="0.1" min="0" max="5" name="rating" id="locRating" value="4.5"></div><div class="col-md-4"><label class="form-label">Image URL</label><input class="form-control" name="image_url" id="locImage"></div></div></div><div class="modal-footer"><button class="btn btn-primary">Lưu</button></div></form></div></div></div>
<script>function resetLocationForm(){document.getElementById('locTitle').textContent='Thêm địa điểm';['locId','locName','locAddress','locDescription','locCost','locImage'].forEach(id=>document.getElementById(id).value='');document.getElementById('locCategory').value='1';document.getElementById('locRating').value='4.5';}function editLocation(r){document.getElementById('locTitle').textContent='Sửa địa điểm';document.getElementById('locId').value=r.id;document.getElementById('locName').value=r.name;document.getElementById('locAddress').value=r.address;document.getElementById('locDescription').value=r.description||'';document.getElementById('locCost').value=r.average_cost;document.getElementById('locRating').value=r.rating;document.getElementById('locImage').value=r.image_url||'';document.getElementById('locCategory').value=r.category_id;}</script>
<?php include __DIR__.'/../includes/footer.php'; ?>
